# Generated by Django 5.2.8 on 2025-11-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postformdb',
            name='message',
            field=models.TextField(),
        ),
    ]
