# Generated by Django 5.2.8 on 2025-11-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postifyapp', '0002_alter_postformdb_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFormDB',
            new_name='PostForm',
        ),
    ]
